"""Deterministic report assembly.

Builds a professional Markdown or HTML assessment report from a workspace's
runs, findings, and an evidence-cited analyst summary. Everything in the report
is grounded: findings cite evidence ids, and the prioritized recommendations
come from the analyst gateway (which rejects ungrounded claims). No network,
no template engine — plain string assembly so output is stable and snapshot-able.
"""

from __future__ import annotations

import html
from datetime import UTC, datetime

from redcalibur_api import vuln_intel
from redcalibur_api.ai import gateway as analyst_gateway
from redcalibur_api.findings import derive_findings
from redcalibur_api.models import (
    AnalystQuestionKind,
    EvidenceItem,
    FindingState,
    Mode,
    Run,
    Workspace,
)


def _summary_counts(findings) -> dict[str, int]:
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "kev": 0}
    for f in findings:
        counts[f.severity_label] = counts.get(f.severity_label, 0) + 1
        if f.kev:
            counts["kev"] += 1
    return counts


def _watermark(mode: Mode) -> str | None:
    if mode == Mode.demo:
        return "DEMO MODE — fixture data only, not a real assessment"
    if mode == Mode.learning:
        return "LEARNING MODE — for training purposes only"
    return None


def build_markdown(
    workspace: Workspace,
    runs: list[Run],
    evidence: list[EvidenceItem],
    generated_at: str | None = None,
    states: dict[str, FindingState] | None = None,
) -> str:
    generated_at = generated_at or datetime.now(UTC).isoformat()
    findings = derive_findings(workspace.id, evidence, states)
    counts = _summary_counts(findings)
    prioritized = analyst_gateway.analyze(AnalystQuestionKind.prioritize, evidence)
    feed = vuln_intel.feed_meta()
    watermark = _watermark(workspace.mode)

    lines: list[str] = []
    if watermark:
        lines.append(f"> ⚠️ **{watermark}**")
        lines.append("")
    lines.append(f"# RedCalibur Assessment Report — {workspace.name}")
    lines.append("")
    lines.append(f"- Workspace: `{workspace.id}`")
    lines.append(f"- Mode: `{workspace.mode.value}`")
    lines.append(f"- Generated: {generated_at}")
    lines.append(f"- Runs recorded: {len(runs)}")
    feed_state = "STALE" if feed.stale else "current"
    lines.append(
        f"- Vulnerability feed: `{feed.feed_id}` generated {feed.generated_at} "
        f"({feed.days_old} day(s) old, {feed_state})"
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"{len(findings)} finding(s): "
        f"{counts['critical']} critical, {counts.get('high', 0)} high, "
        f"{counts['medium']} medium, {counts['kev']} known-exploited (KEV)."
    )
    lines.append("")

    lines.append("## Prioritized Recommendations")
    lines.append("")
    lines.append(f"_{prioritized.headline}_")
    lines.append("")
    if prioritized.claims:
        for claim in prioritized.claims:
            cites = ", ".join(claim.evidence_ids)
            lines.append(f"- {claim.text} _(evidence: {cites})_")
    else:
        lines.append("- No prioritized recommendations: no vulnerability evidence collected.")
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    if findings:
        lines.append("| Priority | Package | Vulnerability | Severity | KEV | Fix | Status | Evidence |")
        lines.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
        for f in findings:
            fix = f.fixed_version or "—"
            kev = "yes" if f.kev else "no"
            lines.append(
                f"| {f.priority_score} | {f.ecosystem}:{f.package} | {f.vuln_id} | "
                f"{f.severity_label} ({f.severity_cvss}) | {kev} | {fix} | {f.status.value} | `{f.evidence_id}` |"
            )
    else:
        lines.append("No vulnerability findings recorded.")
    lines.append("")

    lines.append("## Evidence Index")
    lines.append("")
    for item in evidence:
        lines.append(f"- `{item.id}` — {item.evidence_type}: {item.title}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Report generated by RedCalibur 2.0. All findings are grounded in collected evidence.")
    return "\n".join(lines)


def build_html(
    workspace: Workspace,
    runs: list[Run],
    evidence: list[EvidenceItem],
    generated_at: str | None = None,
    states: dict[str, FindingState] | None = None,
) -> str:
    generated_at = generated_at or datetime.now(UTC).isoformat()
    findings = derive_findings(workspace.id, evidence, states)
    counts = _summary_counts(findings)
    prioritized = analyst_gateway.analyze(AnalystQuestionKind.prioritize, evidence)
    feed = vuln_intel.feed_meta()
    watermark = _watermark(workspace.mode)

    def esc(text: object) -> str:
        return html.escape(str(text))

    watermark_html = (
        f'<div class="watermark">⚠️ {esc(watermark)}</div>' if watermark else ""
    )
    feed_state = "STALE" if feed.stale else "current"

    rows = ""
    for f in findings:
        rows += (
            "<tr>"
            f"<td>{f.priority_score}</td>"
            f"<td>{esc(f.ecosystem)}:{esc(f.package)}</td>"
            f"<td>{esc(f.vuln_id)}</td>"
            f"<td>{esc(f.severity_label)} ({f.severity_cvss})</td>"
            f"<td>{'yes' if f.kev else 'no'}</td>"
            f"<td>{esc(f.fixed_version or '—')}</td>"
            f"<td>{esc(f.status.value)}</td>"
            f"<td><code>{esc(f.evidence_id)}</code></td>"
            "</tr>"
        )
    if not rows:
        rows = '<tr><td colspan="8">No vulnerability findings recorded.</td></tr>'

    recs = ""
    for claim in prioritized.claims:
        cites = ", ".join(esc(e) for e in claim.evidence_ids)
        recs += f"<li>{esc(claim.text)} <span class='cite'>(evidence: {cites})</span></li>"
    if not recs:
        recs = "<li>No prioritized recommendations: no vulnerability evidence collected.</li>"

    evidence_index = "".join(
        f"<li><code>{esc(item.id)}</code> — {esc(item.evidence_type)}: {esc(item.title)}</li>"
        for item in evidence
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>RedCalibur Assessment — {esc(workspace.name)}</title>
<style>
:root {{ color-scheme: light; }}
body {{ font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 880px; color: #1a1a1a; }}
h1 {{ border-bottom: 2px solid #b22; padding-bottom: .4rem; }}
table {{ border-collapse: collapse; width: 100%; font-size: 14px; }}
th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; }}
th {{ background: #f5f5f5; }}
code {{ font-family: ui-monospace, monospace; font-size: 12px; }}
.cite {{ color: #777; font-size: 12px; }}
.meta li {{ color: #444; }}
.watermark {{ background: #fff3cd; border: 1px solid #e0c200; color: #8a6d00;
  padding: 8px 12px; border-radius: 6px; font-weight: 600; margin-bottom: 1rem; }}
</style>
</head>
<body>
{watermark_html}
<h1>RedCalibur Assessment Report — {esc(workspace.name)}</h1>
<ul class="meta">
<li>Workspace: <code>{esc(workspace.id)}</code></li>
<li>Mode: <code>{esc(workspace.mode.value)}</code></li>
<li>Generated: {esc(generated_at)}</li>
<li>Runs recorded: {len(runs)}</li>
<li>Vulnerability feed: <code>{esc(feed.feed_id)}</code> generated {esc(feed.generated_at)} ({feed.days_old} day(s) old, {feed_state})</li>
</ul>
<h2>Summary</h2>
<p>{len(findings)} finding(s): {counts['critical']} critical, {counts.get('high', 0)} high,
{counts['medium']} medium, {counts['kev']} known-exploited (KEV).</p>
<h2>Prioritized Recommendations</h2>
<p><em>{esc(prioritized.headline)}</em></p>
<ul>{recs}</ul>
<h2>Findings</h2>
<table>
<thead><tr><th>Priority</th><th>Package</th><th>Vulnerability</th><th>Severity</th><th>KEV</th><th>Fix</th><th>Status</th><th>Evidence</th></tr></thead>
<tbody>{rows}</tbody>
</table>
<h2>Evidence Index</h2>
<ul>{evidence_index}</ul>
<hr>
<p>Report generated by RedCalibur 2.0. All findings are grounded in collected evidence.</p>
</body>
</html>"""
